### ISSUE TITLE
UnrecognizedTableContent

### ISSUE THREAD

**Issue by puQy** [jessedoyle/prawn-icon#11]
Hey guys,

when i use pdf.table_icon('fa-xyz')  in a single table cell it works fine.
But when i use pdf.table_icon('fa-xyz') combined with a colspan i get the error-message: UnrecognizedTableContent.

example:
data = [ {:content => pdf.table_icon('fa-check'), :colspan => sites.size } ]  --> don't work
data = [ {:content => "#{pdf.table_icon('fa-check'}", :colspan => sites.size } ]  --> don't work

data = [ pdf.table_icon('fa-check') ] --> worked well

Have anyone a suggestion to solve my problem?

**Comment by jessedoyle** [comment]
You can simply pass the `colspan` (or any other valid attribute) directly to the `table_icon` method.

Also note that there is no need to specify the `:content` key, or even explicitly create a hash in the data array:

```ruby
data = [
  [pdf.table_icon('fa-check', colspan: 2)],
  ['One', 'Two']
]

pdf.table(data)
```

Please let me know if this works for you.

**Comment by puQy** [comment]
Nice it works!

Thank you!
