### ISSUE TITLE
Move fonts to data/fonts

### ISSUE THREAD

**Issue by mojavelinux** [jessedoyle/prawn-icon#16]
I think the fonts should be bundled under the path data/fonts instead of fonts to be consistent with other gems and follow the spirit of RubyGems packaging. Fonts are data files needed by the gem and therefore should live in the data directory.

For instance, Prawn itself stores fonts in data/fonts. See https://github.com/prawnpdf/prawn/tree/master/data/fonts

**Comment by jessedoyle** [comment]
Sure! I've thought about this before and I agree that we should be consistent. I'll put together a PR shortly.

As access to the `fonts` directory should be strictly internal, I believe that this should be considered a backward compatible bug fix, therefore it should be fine to increment the minor version to `0.7.1`.

What do you think @mojavelinux?

**Comment by mojavelinux** [comment]
:+1:

**Comment by jessedoyle** [comment]
Merged in c4fee18e9692774ea1d9a7a936c68aede1eeb184. Version `0.7.1` has been pushed to Rubygems!

**Comment by mojavelinux** [comment]
:+1: Super! I'll be sure to use it for Asciidoctor PDF 1.5.0.beta.1.
