### ISSUE TITLE
update font awesome to latest version

### ISSUE THREAD

**Issue by jlozadad** [jessedoyle/prawn-icon#32]
is it possible to update to latest version?

**Comment by jlozadad** [comment]
thanks for the info! I'll check it out and see what I can do.

**Comment by jessedoyle** [comment]
@jlozadad - I've started a branch [here](https://github.com/jessedoyle/prawn-icon/pull/33). I was hoping to avoid breaking changes as much as possible, but it looks like FontAwesome split up their icons into multiple font files.

Do you mind trying out the branch? I'd like to get your opinion on the changes.

Thanks!

**Comment by jessedoyle** [comment]
Fixed in https://github.com/jessedoyle/prawn-icon/pull/33
