### ISSUE TITLE
table_icon doesn't work with content key

### ISSUE THREAD

**Issue by lethunder** [jessedoyle/prawn-icon#39]
hello guys,
i'm not able to use table_icon in my table. i can't use the classic call because my table has col and row span

table([
 ["A", {:content => table_icon('fas-birthday-cake'), :colspan => 2}, "B"],
 [{:content => "1x2", :rowspan => 2}, "C", "D", "E"],
 [{:content => "2x2", :colspan => 2, :rowspan => 2}, "F"],
 ["G", "H"]
])

This does not work. It returns WARN: Prawn::Errors::UnrecognizedTableContent: Prawn::Errors::UnrecognizedTableContent

**Comment by jessedoyle** [comment]
Hi @lethunder! Thanks for using `Prawn::Icon`!

If I recall correctly, I believe the `table_icon` method accepts an options hash.

Do you mind giving this a try?

```ruby
table([
  ["A", table_icon('fas-birthday-cake', colspan: 2), "B"],
  [{:content => "1x2", :rowspan => 2}, "C", "D", "E"],
  [{:content => "2x2", :colspan => 2, :rowspan => 2}, "F"],
  ["G", "H"]
])
```

This is producing the following output with Prawn `2.1.0` for me:

<img width="178" alt="Screen Shot 2019-09-06 at 8 10 45 AM" src="https://user-images.githubusercontent.com/6474230/64434513-ec922180-d07d-11e9-95c4-69aa804ba948.png">

Please let me know if this solves your issue!

**Comment by lethunder** [comment]
Hey. Thanks for your quick response! It works.

Le ven. 6 sept. 2019 à 16:11, Jesse Doyle <notifications@github.com> a
écrit :

**Comment by jessedoyle** [comment]
Thanks @lethunder. I'll close this issue then!
