### ISSUE TITLE
icon in string interpolation inside prawn text method fails to render

### ISSUE THREAD

**Issue by atstockland** [jessedoyle/prawn-icon#51]
If I use 

    text "Test: #{ icon 'fa-helicopter', size: 6 }", size: 9, color: '555555', inline_format: true

I get 

<img width="25" alt="image" src="https://user-images.githubusercontent.com/536711/105614736-01a94680-5d80-11eb-87df-dce76e4622e1.png"> Test: #Prawn::Icon:0x00007fba4a9b68e0>

the expected outcome is

Test: <img width="25" alt="image" src="https://user-images.githubusercontent.com/536711/105614736-01a94680-5d80-11eb-87df-dce76e4622e1.png">

Am I using this incorrectly or is string interpolation not supported?

**Comment by jessedoyle** [comment]
Hey @atstockland, thanks for using `Prawn::Icon`!

There's no need to use Prawn's `text` method directly for inline-formatted icons.

This snippet should work:

```ruby
icon 'Test: <icon size="6">fas-helicopter</icon>', size: 9, color: '555555', inline_format: true
```

**Comment by atstockland** [comment]
Thanks!  I misread the docs.  That works great.
