### ISSUE TITLE
Support for material icons

### ISSUE THREAD

**Issue by markcraig** [jessedoyle/prawn-icon#57]
We plan to use Antora Assembler, which relies on `asciidoctor-pdf` to generate PDFs, which in turn relies on `prawn-icon` for icon support.

We are increasingly using [material icons](https://developers.google.com/fonts/docs/material_icons) in our UIs and therefore in our docs.

It would be great if prawn-icon could add support for material icons to make them easy to use when creating PDFs.

**Comment by mojavelinux** [comment]
If this proposal is accepted, I suggest using the icon prefix "mi". This follows the naming pattern used for foundation icons.

**Comment by mojavelinux** [comment]
I appears that this was implemented, merged, and released. Is that correct? If so, I would recommend closing this issue to avoid confusion.

**Comment by markcraig** [comment]
Great news! Looking forward to being able to use these in asciidoctor-pdf going forward

**Comment by jessedoyle** [comment]
We did cut release [3.1.0](https://github.com/jessedoyle/prawn-icon/releases/tag/v3.1.0) last week that includes support for Material Design Icons.

It's worthwhile to note that the Material _Design_ Icons collection includes the base icon set from Google as well as a large number of community-maintained icons. The full set can be viewed [here](https://materialdesignicons.com).

With that being said, I'm going to close this issue. Thanks!
