### ISSUE TITLE
Support for Material Design Icons

### ISSUE THREAD

**Issue by maneex** [jessedoyle/prawn-icon#58]
Hello,

  In our interfaces, we are using Material Design Icons (https://materialdesignicons.com/), and we're using AsciiDoctor to generate our documentation.

  Would you agree to add the Material Design Icon set to Prawn ? I can prepare a PR following the requirements you specified in #57 .

  I guess the proper prefix would be 'mdi'.

Thank you !

**Comment by jessedoyle** [comment]
Hi @maneex - thanks for using `Prawn::Icon`. Please feel free to submit a PR to add Material Design Icons to this library - I would absolutely support that feature.

From the discussion in #57, I believe we landed on `mi` for the font prefix. Thanks!

**Comment by maneex** [comment]
Hello @jessedoyle ! Thanks for your quick answer.

Please be careful that #57 mentions "Material Icons" from google (https://fonts.google.com/icons) while we are using "Material Design Icons" (https://materialdesignicons.com/). 

To my understanding, for "Material Design Icon", we should use `mdi` as the font prefix, because in CSS all the font labels are prefixed by `mdi-`, as they are by `fa-` in FontAwesome (But I might be wrong).

I'll submit the PR in a few minutes. You'll tell me if something has to be changed/modified. By the way, you did a really nice job: I've been able to add the font quickly while I never worked with ruby nor with fonts at all.

**Comment by jessedoyle** [comment]
Hey @maneex - I'm closing this in favour of https://github.com/jessedoyle/prawn-icon/issues/57 as they both reference the same issue.

Thanks again for the PR!

**Comment by jessedoyle** [comment]
Actually... I realize I'm mistaking Material _Design_ Icons and Material Icons, sorry for the mixup!
