### ISSUE TITLE
Icons in tables

### ISSUE THREAD

**Issue by dguettler** [jessedoyle/prawn-icon#6]
Any suggestion how or if at all you could get this to work inside tables?
Currently it throws an `UnrecognizedTableContent` error if you try to pass an icon as content for a table cell.

Thanks, Daniel

**Comment by jessedoyle** [comment]
Are you currently using ```inline_format: true``` for the content inside the table cell?

It'd be awesome if you could post a code sample that causes the issue so I can research it.

**Comment by jessedoyle** [comment]
Actually I just did some thinking. The following code should create an icon within a table cell:
```ruby
require 'prawn'
require 'prawn/table'
require 'prawn/icon'

Prawn::Document.generate('test.pdf') do |pdf|
  # Create a new icon instance, but don't render it yet...
  arrows = Prawn::Icon.new('fa-arrows', pdf)
  
  data = [
    # Grab the unicode value for the particular icon
    [{ font: 'fa', content: arrows.unicode }],
    ['Test']
  ]

  pdf.table(data)
end
```

I admit that the above code is quite "hack-ish". It would be worthwhile to provide a standardized method to render icons within table cells.

Ideally, I think adding a ```table_icon(args)``` method to ```prawn/icon``` that simply returns a hash that contains ```font``` and ```content``` keys should provide simple access to this functionality.

I'll keep this issue open as I look into adding this method in the future.

**Comment by dguettler** [comment]
Hi Jesse,

I was just about to give you a code example. I'll give your hack-ish solution a try.
Before I naively tried to pass `pdf.icon` or `pdf.make_icon` as the content for a table cell.

```
pdf.table([
  [
    pdf.icon('fa-check-square-o'),
    pdf.make_icon('fa-check-square-o'),
  ]
])
```

which was rising above exception as table checks the `content` for allowed types.

I think having a `pdf.table_icon(args)` method would be a great addition to make this more accessible.

Best, Daniel

**Comment by jessedoyle** [comment]
Daniel,

Please see pull request #7. I have added a `table_icon` method to the code base and sample code is included in the pull request.

This change will be released in the next version of `prawn/icon`.

**Comment by dguettler** [comment]
Jesse,

Looks great thanks for getting this feature in so quickly.

Best, Daniel
